### ISSUE TITLE
Dependency clean-up not performed

### ISSUE THREAD

**Issue by bgiot** [DataBooster/NupkgMerge#1]
We have a package A that depends on package B.  If we merge A (as primary) and B (as secondary), the resulting nupkg should not contain anymore the dependency to B package.

**Comment by AbelCheng** [comment]
Sorry for causing confusion.

Originally, the purpose of this tool is to merge multiple target frameworks for the same NuGet ID. It does not cover wide meaning of merging any two completely different packages.

For example,
We have a package `A45.nupkg` (the target framework is _.Net 4.5_), we also have a package `A40.nupkg` (the target framework is _.Net 4.0_), `A40.nupkg` and `A45.nupkg` are the same NuGet ID **`A`** -- this is the key condition, then `A45.nupkg` and `A40.nupkg` can be merged into one package `A.nupkg` (multi-target framework - _.Net 4.0_ and _.Net 4.5_ in a single package) for publishing.
